import "./globals.css";

export const metadata = {
  title: "Renovation Site Mock Design",
  description: "Generated by Finnep Fi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
